#pragma once

#include "driver/gpio.h"
#include "driver/i2c_master.h"
#include "driver/i2s_std.h"
#include "driver/ledc.h"
#include "driver/spi_master.h"

#define HARDWARE_BOARD_TYPE                     "wt9932p4c61_tiny_qiming"

#define HARDWARE_BOARD_BOOT_BUTTON_GPIO         GPIO_NUM_35
#define HARDWARE_BOARD_RGB_LED_GPIO             GPIO_NUM_51

#define HARDWARE_BOARD_I2C_NUM                  I2C_NUM_0
#define HARDWARE_BOARD_I2C_SDA                  GPIO_NUM_7
#define HARDWARE_BOARD_I2C_SCL                  GPIO_NUM_8
#define HARDWARE_BOARD_I2C_FREQ_HZ              400000
#define HARDWARE_BOARD_I2C_PROBE_TIMEOUT_MS      200

#define HARDWARE_BOARD_DISPLAY_ENABLED          1
#define HARDWARE_BOARD_TOUCH_ENABLED            1
#define HARDWARE_BOARD_LCD_WIDTH                640
#define HARDWARE_BOARD_LCD_HEIGHT               480
#define HARDWARE_BOARD_LCD_PHYSICAL_WIDTH       480
#define HARDWARE_BOARD_LCD_PHYSICAL_HEIGHT      640
#define HARDWARE_BOARD_LCD_CONTROLLER_I2C_ADDR  0x28
#define HARDWARE_BOARD_TOUCH_CONTROLLER_I2C_ADDR 0x55
#define HARDWARE_BOARD_LCD_BACKLIGHT_GPIO       GPIO_NUM_26
#define HARDWARE_BOARD_LCD_RESET_GPIO           GPIO_NUM_27
#define HARDWARE_BOARD_LCD_RESET_ASSERT_MS       20
#define HARDWARE_BOARD_LCD_RESET_SETTLE_MS      120
#define HARDWARE_BOARD_UI_PROBE_ATTEMPTS          3
#define HARDWARE_BOARD_UI_PROBE_RETRY_MS          50

#define HARDWARE_BOARD_AUDIO_ENABLED            0
#define HARDWARE_BOARD_AUDIO_I2S_PORT           I2S_NUM_0
#define HARDWARE_BOARD_AUDIO_LRCK               GPIO_NUM_NC
#define HARDWARE_BOARD_AUDIO_MCLK               GPIO_NUM_NC
#define HARDWARE_BOARD_AUDIO_BCLK               GPIO_NUM_NC
#define HARDWARE_BOARD_AUDIO_DIN                GPIO_NUM_NC
#define HARDWARE_BOARD_AUDIO_DOUT               GPIO_NUM_NC
#define HARDWARE_BOARD_AUDIO_PA_GPIO            GPIO_NUM_NC
#define HARDWARE_BOARD_AUDIO_SAMPLE_RATE_HZ     16000
#define HARDWARE_BOARD_AUDIO_BITS_PER_SAMPLE    16
#define HARDWARE_BOARD_AUDIO_CHANNELS           2
#define HARDWARE_BOARD_AUDIO_ADC_CHANNELS       2
#define HARDWARE_BOARD_AUDIO_ADC_TDM_CHANNELS   2
#define HARDWARE_BOARD_AUDIO_ADC_CHANNEL_MASK   0x03
#define HARDWARE_BOARD_AUDIO_ADC_PRIMARY_CHANNEL 0
#define HARDWARE_BOARD_AUDIO_ADC_REFERENCE_CHANNEL 1
#define HARDWARE_BOARD_AUDIO_DEFAULT_VOLUME     70
#define HARDWARE_BOARD_AUDIO_DEFAULT_ADC_GAIN_DB 24.0f

#define HARDWARE_BOARD_CAMERA_ENABLED           1
#define HARDWARE_BOARD_CAMERA_I2C_NUM           I2C_NUM_0
#define HARDWARE_BOARD_CAMERA_I2C_FREQ_HZ       400000
#define HARDWARE_BOARD_CAMERA_I2C_ADDR           0x30
#define HARDWARE_BOARD_CAMERA_POWER_GPIO        GPIO_NUM_0
#define HARDWARE_BOARD_CAMERA_POWER_OFF_MS        50
#define HARDWARE_BOARD_CAMERA_POWER_SETTLE_MS    150
#define HARDWARE_BOARD_CAMERA_PROBE_ATTEMPTS       3
/*
 * GPIO0 supplies and releases the SC2336. esp_video registers the sensor once,
 * so keep the rail enabled across camera clients to preserve the sensor state
 * and make QR/call/IPC transitions deterministic.
 */
#define HARDWARE_BOARD_CAMERA_KEEP_POWERED       1
#define HARDWARE_BOARD_CAMERA_WIDTH             1024
#define HARDWARE_BOARD_CAMERA_HEIGHT            600
#define HARDWARE_BOARD_CAMERA_FPS               30
#define HARDWARE_BOARD_CAMERA_BUFFER_COUNT      3
